name: Publish to npm and crates.io

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v0.1.0, v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TypeScript/npm publishing
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install TypeScript dependencies
        working-directory: ./typescript
        run: npm install

      - name: Build TypeScript package
        working-directory: ./typescript
        run: npm run build

      - name: Publish to npm
        working-directory: ./typescript
        run: npm publish --access public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Rust/crates.io publishing
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Publish to crates.io
        working-directory: ./rust
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
